# Generated by Django 4.2.5 on 2023-12-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recycle', '0002_alter_usuario_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='id_evento',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
