# Generated by Django 4.2.5 on 2023-12-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recycle', '0005_alter_usuario_options_alter_usuario_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='id_evento',
            field=models.CharField(default='a', max_length=50),
        ),
    ]
