# Generated by Django 4.2.5 on 2023-12-04 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recycle', '0003_rename_contrasena_usuario_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_active',
        ),
    ]
