# Generated by Django 4.2.5 on 2023-12-04 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recycle', '0003_usuario_id_evento'),
        ('Recycle', '0006_usuario_id_evento'),
    ]

    operations = [
    ]
